# Generated by Django 3.1.3 on 2021-11-16 20:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('access_level', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('rate', models.CharField(max_length=10)),
                ('rules', models.TextField(default=' ')),
                ('release_date', models.DateField(default=datetime.datetime(2021, 11, 16, 20, 38, 13, 446176, tzinfo=utc))),
                ('site', models.CharField(max_length=20)),
                ('number_of_rules', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('development_budget', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_email', models.CharField(max_length=30)),
                ('review_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=' ')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplusapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField(default=' ')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_b', to='gameplusapp.employee')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id_b', to='gameplusapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='GameDevelopmentStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime(2021, 11, 16, 20, 38, 13, 446176, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2021, 11, 16, 20, 38, 13, 447153, tzinfo=utc))),
                ('stage_description', models.TextField(default=' ')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplusapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='ContractOfDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_date', models.DateField(default=datetime.datetime(2021, 11, 16, 20, 38, 13, 448129, tzinfo=utc))),
                ('contract_end_date', models.DateField(default=datetime.datetime(2021, 11, 16, 20, 38, 13, 448129, tzinfo=utc))),
                ('development_full_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_a', to='gameplusapp.employee')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id_a', to='gameplusapp.employee')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplusapp.game')),
            ],
        ),
    ]
